---
name: Addressable
---

SilverStripeAddressable\Extensions\GoogleGeocoding:
  google_api_url: 'https://maps.googleapis.com/maps/api/geocode/xml'
  google_api_key: ''

SilverStripeAddressable\Extensions\Geocodable:
  is_geocodable: true
